steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - lead_match_reporting_app/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-repo/lead-match-reporting-app:$SHORT_SHA
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-repo/lead-match-reporting-app:latest
      - .

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-repo/lead-match-reporting-app:$SHORT_SHA
  - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-repo/lead-match-reporting-app:latest
