#DATABASE coniguration 
DB_SCHEMA=lead_mgmt_qat
DB_CONNECTION_NAME=p-601-np-bcleadsmgmt-qat:us-central1:lead-mgmt-qat
POSTGRES_DB_NAME=lead-mgmt-db
POSTGRES_DB_USER=gco-iam-svc-lead-mgmt-bc-qat@p-601-np-bcleadsmgmt-qat.iam
GCP_PROJECT_ID=p-601-np-bcleadsmgmt-qat
CLOUD_SQL_IP_TYPE=PRIVATE
BATCH_ID=

#SNOW Configuration
LEAD_URL=https://costcobizsvctest.service-now.com/api/sn_retail/lead_pos_data/getLead
POS_URL=https://costcobizsvctest.service-now.com/api/sn_retail/lead_pos_data/getPOS_new
MATCH_RESULT_URL=https://costcobizsvctest.service-now.com/api/sn_retail/pos_creation/insertposdata
SNOW_USER=lead_mgmt_snow_user
SNOW_PASSWORD=lead_mgmt_snow_password
BATCH_SIZE=10000

#STORAGE Configuration
INPUT_BUCKET_NAME=gcp-gcs-lead-mgmt-us-qat
ARCHIVE_BUCKET_NAME=gcp-gcs-lead-mgmt-us-qat
POS_BUCKET_NAME=gcp-gcs-lead-mgmt-us-qat-pos-raw
LEAD_INPUT_FOLDER=staging/lead
CONTACT_INPUT_FOLDER=staging/contact/customer_contact.csv
POS_INPUT_FOLDER=staging/pos
DATA_LOAD_TYPE=delta
MATCH_RESULT_INPUT_FOLDER=match_result
ARCHIVE_FOLDER=archive
SERVICE_ACCOUNT=gco-iam-svc-lead-mgmt-bc-qat@p-601-np-bcleadsmgmt-qat.iam.gserviceaccount.com
NETWORK=gcp-vpc-np-host
SUBNET=gcp-snt-np-usc1-601-cloudrunjobs-np
JOB_NAME=lead-match-job
FILE_TYPE=json
FILE_ENCODING=utf-8
CONFIG_FILE_PATH=configuration_qat.ini
LOG_LEVEL=DEBUG
GCS_DESTINATION_PREFIX=pos-raw-data/incoming-files
DRIVE_FOLDER_ID=1FdNywx_ReYaY530imMapzIVZoBV_ZnOJ
REQUESTS_CA_BUNDLE=/etc/ssl/costco/costco-tlsi.crt