#DATABASE coniguration 
DB_SCHEMA=lead_mgmt_adt
DB_CONNECTION_NAME=p-601-np-bcleadsmgmt-adt:us-central1:lead-mgmt-adt
POSTGRES_DB_NAME=lead-mgmt-db
POSTGRES_DB_USER=gco-iam-svc-lead-mgmt-bc-adt@p-601-np-bcleadsmgmt-adt.iam
GCP_PROJECT_ID=p-601-np-bcleadsmgmt-adt
CLOUD_SQL_IP_TYPE=PRIVATE

#SNOW Configuration
LEAD_URL=https://costcobizsvctest.service-now.com/api/sn_retail/lead_pos_data/getLead
POS_URL=https://costcobizsvctest.service-now.com/api/sn_retail/lead_pos_data/getpos
MATCH_RESULT_URL=https://costcobizsvctest.service-now.com/api/sn_retail/lead_pos_data/updatelead
SNOW_USER=lead_mgmt_snow_user
SNOW_PASSWORD=lead_mgmt_snow_password
BATCH_SIZE=5000

#STORAGE Configuration
INPUT_BUCKET_NAME=gcp-gcs-lead-mgmt-us-adt
ARCHIVE_BUCKET_NAME=gcp-gcs-lead-mgmt-us-adt
LEAD_INPUT_FOLDER=staging/lead
CONTACT_INPUT_FOLDER=staging/contact/customer_contact.csv
POS_INPUT_FOLDER=staging/pos
DATA_LOAD_TYPE=delta
MATCH_RESULT_INPUT_FOLDER=match_result
ARCHIVE_FOLDER=archive
SERVICE_ACCOUNT=gco-iam-svc-lead-mgmt-bc-adt@p-601-np-bcleadsmgmt-adt.iam.gserviceaccount.com
NETWORK=gcp-vpc-np-host
SUBNET=gcp-snt-np-usc1-601-cloudrunjobs-np
JOB_NAME=lead-match-job
FILE_TYPE=json
FILE_ENCODING=utf-8
CONFIG_FILE_PATH=configuration_adt.ini