PROJECT_ID=p-601-pd-bcleadsmgmt-prd
SERVICE_ACCOUNT=gco-iam-svc-lead-mgmt-bc-prd@p-601-pd-bcleadsmgmt-prd.iam.gserviceaccount.com
GCS_BUCKET=gcp-gcs-lead-mgmt-us-prd
REGION=us-central1
JOB_NAME=lead-match-job
VERSION=1.0.0
NETWORK=gcp-vpc-pd-host
SUBNET=gcp-snt-pd-usc1-601-cloudrunjobs-pd
ARTIFACT_REGISTRY_URL=https://us-kfp.pkg.dev/p-601-np-bcleadsmgmt-adt/gcp-lead-mgmt-kubeflow
PIPELINE_NAME=lead-match-pipeline
VERTEX_AI_NETWORK=projects/525181271691/global/networks/gcp-vpc-pd-host
CONFIG_FILE_PATH=configuration_prd.ini
CPU_LIMIT=8
MEMORY_LIMIT=2G
MACHINE_TYPE=n2-standard-8
MAX_WORKERS=2
CPU_LIMIT_EG=8
MEMORY_LIMIT_EG=32G
MATCH_URL=https://costcobizsvctest.service-now.com/api/sn_retail/pos_creation/insertposdata
KFP_CUSTOM_IMAGE=us-docker.pkg.dev/gcp-prj-images/gcp-gar-repo-mbrshp/lead-mgmt:latest
MATCH_ID=