PROJECT_ID=p-601-np-bcleadsmgmt-adt
SERVICE_ACCOUNT=gco-iam-svc-lead-mgmt-bc-adt@p-601-np-bcleadsmgmt-adt.iam.gserviceaccount.com
GCS_BUCKET=gcp-gcs-lead-mgmt-us-adt
REGION=us-central1
JOB_NAME=lead-match-job
VERSION=1.0.0
NETWORK=gcp-vpc-np-host
SUBNET=gcp-snt-np-usc1-601-cloudrunjobs-np
ARTIFACT_REGISTRY_URL=https://us-kfp.pkg.dev/p-601-np-bcleadsmgmt-adt/gcp-lead-mgmt-kubeflow
PIPELINE_NAME=lead-match-pipeline
VERTEX_AI_NETWORK=projects/525181271691/global/networ4s/gcp-vpc-np-host
CONFIG_FILE_PATH=configuration_adt.ini
CPU_LIMIT=8
MEMORY_LIMIT=2G
MACHINE_TYPE=n2-standard-8
MAX_WORKERS=4
CPU_LIMIT_EG=8
MEMORY_LIMIT_EG=32G
MATCH_URL=https://costcobizsvctest.service-now.com/api/sn_retail/lead_pos_data/updatelead
KFP_CUSTOM_IMAGE=us-docker.pkg.dev/gcp-prj-images/gcp-gar-repo-mbrshp/lead-mgmt:latest