PROJECT_ID=p-601-lab-bc-leads-mgmt
KFP_CUSTOM_IMAGE=gcr.io/${PROJECT_ID}/kbf_image
SERVICE_ACCOUNT=lead-management@${PROJECT_ID}.iam.gserviceaccount.com
GCS_BUCKET=leads_management_solution
REGION=us-central1
JOB_NAME=lead-match-job
VERSION=1.0.0
NETWORK=lead-mgmt-vpc
SUBNET=lead-mgmt-vpc
REGISTRY_URL=https://${REGION}-kfp.pkg.dev/${PROJECT_ID}/lead-mgmt-repo
PIPELINE_NAME=lead-match-pipeline
VERTEX_AI_NETWORK=projects/554682760979/global/networks/lead-mgmt-vpc
CONFIG_FILE_PATH=config_lead_mgmt_dev.ini
CPU_LIMIT=4
MEMORY_LIMIT=16G
MACHINE_TYPE=n2-standard-8
MAX_WORKERS=8
CPU_LIMIT_EG=8
MEMORY_LIMIT_EG=32G
