#DATABASE coniguration 
DB_SCHEMA=lead_mgmt_costco
DB_CONNECTION_NAME="p-601-lab-bc-leads-mgmt:us-central1:lead-mgmt-dev"
POSTGRES_DB_NAME=postgres
POSTGRES_DB_USER=lead_mgmt_posgres_db_user
POSTGRES_DB_PASSWORD_ID=lead_mgmt_posgres_db_password
GCP_PROJECT_ID=p-601-lab-bc-leads-mgmt
CLOUD_SQL_IP_TYPE=PRIVATE

#SNOW Configuration
LEAD_URL=https://costcobizsvctest.service-now.com/api/sn_retail/lead_pos_data/getLead
POS_URL=https://costcobizsvctest.service-now.com/api/sn_retail/lead_pos_data/getpos
MATCH_RESULT_URL=https://costcobizsvctest.service-now.com/api/sn_retail/lead_pos_data/updatelead
SNOW_USER=lead_mgmt_snow_user
SNOW_PASSWORD=lead_mgmt_snow_password
BATCH_SIZE=5000

#STORAGE Configuration
INPUT_BUCKET_NAME=leads_management_solution
ARCHIVE_BUCKET_NAME=leads_management_solution
LEAD_INPUT_FOLDER=staging/lead
CONTACT_INPUT_FOLDER=staging/contact/customer_contact.csv
POS_INPUT_FOLDER=staging/pos
DATA_LOAD_TYPE=delta
MATCH_RESULT_INPUT_FOLDER=match_result
ARCHIVE_FOLDER=archive
SERVICE_ACCOUNT=lead-management@p-601-lab-bc-leads-mgmt.iam.gserviceaccount.com
DOCKER_IMAGE_NAME=sync_snow_gcp_job
DOCKER_VERSION=$1
NETWORK=lead-mgmt-vpc
SUBNET=lead-mgmt-vpc
JOB_NAME=lead-match-job
FILE_TYPE=json
FILE_ENCODING=utf-8