-- Grant permissions on the database

GRANT ALL PRIVILEGES ON DATABASE "$DATABASE_NAME" TO "$IAM_USER";

-- Create application schema

CREATE SCHEMA IF NOT EXISTS "$SCHEMA_NAME";

-- Set default privileges for the service account
GRANT USAGE, CREATE ON SCHEMA "$SCHEMA_NAME" TO "$IAM_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA "$SCHEMA_NAME" GRANT ALL ON TABLES TO "$IAM_USER";

-- Create vector extension
CREATE EXTENSION IF NOT EXISTS vector; -- installs into public

-- create pgaudit extension
CREATE EXTENSION IF NOT EXISTS pgaudit;

-- Grant same privileges to new user
GRANT ALL PRIVILEGES ON DATABASE "lead-mgmt-db" TO "$NEW_IAM_USER";
GRANT ALL PRIVILEGES ON SCHEMA  "$SCHEMA_NAME" TO "$NEW_IAM_USER";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA  "$SCHEMA_NAME" TO "$NEW_IAM_USER";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA  "$SCHEMA_NAME" TO "$NEW_IAM_USER";