-- Reassign ownership
REASSIGN OWNED BY "$IAM_USER" TO "$NEW_IAM_USER";

-- Grant same privileges to new user
GRANT ALL PRIVILEGES ON DATABASE "lead-mgmt-db" TO "$NEW_IAM_USER";
GRANT ALL PRIVILEGES ON SCHEMA  "$SCHEMA_NAME" TO "$NEW_IAM_USER";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA  "$SCHEMA_NAME" TO "$NEW_IAM_USER";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA  "$SCHEMA_NAME" TO "$NEW_IAM_USER";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA  "$SCHEMA_NAME" TO "$NEW_IAM_USER";

-- (Optional) Remove old user's privileges
DROP OWNED BY "$IAM_USER";