permissions:
  contents: read
name: Terraform View Remote State Without Code

on:
  workflow_dispatch:  # run manually

jobs:
  view-state:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout (empty repo)
      uses: actions/checkout@v4

    - name: "Auth in GCP"
      id: "auth"
      uses: "google-github-actions/auth@v2"
      with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
          project_id: 'p-601-np-membership-adt'

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Create minimal Terraform backend config
      run: |
        cat > main.tf <<EOF
        terraform {
          backend "gcs" {
            bucket = "gcp-gcs-cicd-core-mbr-bc-lead"
            prefix = "adt/bc"
          }
        }
        EOF

    - name: Initialize Terraform backend
      run: terraform init -input=false

    - name: List resources in remote state
      run: terraform state list

    - name: Destroy specific resource
      run: terraform destroy -auto-approve -target=module.monitoring_alert.google_monitoring_alert_policy.cloud_run_job_failure
