name: deploy-lead-match-job

on:
  push:
    branches:
      - main
      - 'feature**'
    tags:
      - tag_spt
      - tag_prod
    paths:
      - .github/workflows/cloud_run_job_deployment.yml
      - cloud_run_job/**

jobs:
  build-and-deploy:
    runs-on:
      - self-hosted
      - us-west1
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine environment and conditions
        id: config
        run: |
          REF_NAME="${GITHUB_REF_NAME}"
          REF="${GITHUB_REF}"

          if [[ "$REF" == refs/heads/feature** ]]; then
            echo "ENV=adt" >> $GITHUB_ENV
            echo "DEPLOY=true" >> $GITHUB_ENV
            echo "BUILD_IMAGE=true" >> $GITHUB_ENV
            echo "PROJECT_ID=p-601-np-membership-adt" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=gco-iam-svc-mbr-bc-adt@p-601-np-membership-adt.iam.gserviceaccount.com" >> $GITHUB_ENV

          elif [[ "$REF" == refs/heads/main ]]; then
            echo "ENV=qat" >> $GITHUB_ENV
            echo "DEPLOY=true" >> $GITHUB_ENV
            echo "BUILD_IMAGE=false" >> $GITHUB_ENV
            echo "PROJECT_ID=p-601-np-membership-qat" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=gco-iam-svc-mbr-bc-qat@p-601-np-membership-qat.iam.gserviceaccount.com" >> $GITHUB_ENV

          elif [[ "$REF" == refs/tags/tag_spt ]]; then
            echo "ENV=spt" >> $GITHUB_ENV
            echo "DEPLOY=true" >> $GITHUB_ENV
            echo "BUILD_IMAGE=false" >> $GITHUB_ENV
            echo "PROJECT_ID=p-601-np-membership-spt" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=gco-iam-svc-mbr-bc-spt@p-601-np-membership-spt.iam.gserviceaccount.com" >> $GITHUB_ENV

          else
            echo "DEPLOY=false" >> $GITHUB_ENV
            echo "BUILD_IMAGE=false" >> $GITHUB_ENV
          fi

         # elif [[ "$REF" == refs/tags/tag_prod ]]; then
          #  echo "ENV=prod" >> $GITHUB_ENV
          #  echo "DEPLOY=true" >> $GITHUB_ENV
          #  echo "BUILD_IMAGE=false" >> $GITHUB_ENV
          #  echo "PROJECT_ID=p-601-prd-membership-prd" >> $GITHUB_ENV
          #  echo "SERVICE_ACCOUNT=gco-iam-svc-mlty-dbt-prd@p-601-prd-membership-prd.iam.gserviceaccount.com" >> $GITHUB_ENV

       
      - name: Set up Python
        if: env.BUILD_IMAGE == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.16'

      - name: Install build dependencies
        if: env.BUILD_IMAGE == 'true'
        run: |
         pip install build wheel setuptools Cython

      - name: Build wheel
        if: env.BUILD_IMAGE == 'true'
        run: |
          rm -f ./cloud_run_job/*.whl
          cd ./lead_match_codebase
          python -m build --wheel
          cp dist/*.whl ../cloud_run_job/
          cd ..

      - name: Login to GitHub Container Registry
        if: env.BUILD_IMAGE == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Auth to GCP
        if: env.DEPLOY == 'true'
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL}}

      - name: Login to Google Artifact Registry
        if: env.DEPLOY == 'true'
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Docker Buildx
        if: env.BUILD_IMAGE == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        if: env.BUILD_IMAGE == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            us-docker.pkg.dev/gcp-prj-images/gcp-gar-repo-mbrshp/lead-match-job

      - name: Build and push Docker image
        if: env.BUILD_IMAGE == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./cloud_run_job
          file: ./cloud_run_job/Dockerfile
          push: true
          tags: us-docker.pkg.dev/gcp-prj-images/gcp-gar-repo-mbrshp/lead-match-job:latest

      - name: Deploy to Cloud Run Job
        if: env.DEPLOY == 'true'
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          job: 'lead-match-job'
          image: 'us-docker.pkg.dev/gcp-prj-images/gcp-gar-repo-mbrshp/lead-match-job:latest'
          project_id: ${{ env.PROJECT_ID }}
          flags: |
            --service-account=${{ env.SERVICE_ACCOUNT }}
            --vpc-egress=all-traffic
            --network=gcp-vpc-np-host

      - name: Describe deployed job
        if: env.DEPLOY == 'true'
        run: |
          gcloud run jobs describe lead-match-job \
            --region us-central1 \
            --project ${{ env.PROJECT_ID }} \
            --format="yaml"
