name: container-test
on:
  #Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - .github/workflows/cloud_run_job_deployment.yml
      - cloud-run-job/**

jobs:
  build-and-push-container:
    name: Build and Push Container
    runs-on:
      - self-hosted
      - us-west1
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: auth
        name: Auth to GCP for GAR service account
        uses : google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID}}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL}}
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/membership/lead-management/lead-match-job
            us-docker.pkg.dev/gcp-prj-images/gcp-gar-repo-mbrshp/lead-match-job
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          context: ./cloud-run-job
          file: ./cloud-run-job/Dockerfile
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: us-docker.pkg.dev/gcp-prj-images/gcp-gar-repo-mbrshp/lead-match-job:latest 

      - name: 'Deploy cloud run job with gcloud'
        run: |
          IMAGE="us-docker.pkg.dev/gcp-prj-images/gcp-gar-repo-mbrshp/lead-match-job:latest"
          gcloud run jobs deploy lead-match-job \
          --image $IMAGE \
          --region us-central1 \
          --project p-601-np-membership-adt \
          --format json

      - name: 'Describe deployed job'
        run: |
          gcloud run jobs describe lead-match-job \
            --region us-central1 \
            --project p-601-np-membership-adt \
            --format="yaml"
