name: Enable Cloud SQL Point-in-Time Recovery

on:
  workflow_dispatch:   # manual trigger from GitHub UI

jobs:
  enable-pitr:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}

      - name: Enable Point-in-Time Recovery spt
        run: |
          unset CLOUDSDK_CORE_PROJECT
          gcloud config set project p-601-np-bcleadsmgmt-spt
          gcloud sql instances patch lead-mgmt-spt \
            --enable-point-in-time-recovery \
            --quiet
      - name: Enable Point-in-Time Recovery qat
        run: |
          unset CLOUDSDK_CORE_PROJECT
          gcloud config set project p-601-np-bcleadsmgmt-qat
          gcloud sql instances patch lead-mgmt-qat \
            --enable-point-in-time-recovery \
            --quiet
