name: "google_auth"

on:
  workflow_dispatch:  # Trigger manually

env:
  PROJECT_ID: 'p-601-np-membership-adt' # TODO: update to your Google Cloud project ID
  REGION: 'us-central1' # TODO: update to your region

jobs:
  run:
    name: "auth"
    runs-on: "ubuntu-latest"
    environment: ${{ github.event.pull_request.head.ref }}
    strategy:
      matrix:
        env: ['adt'] #,['adt', 'qat', 'spt'] # Exclude prd from auto-plan
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Auth in GCP"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
          
      # - name: "Setup Terraform"
      #   uses: hashicorp/setup-terraform@v3

      # - name: "Terraform Init"
      #   working-directory: ./terraform/environments/${{ matrix.env }}
      #   run: terraform init

      # - name: "Terraform Plan"
      #   working-directory: ./terraform/environments/${{ matrix.env }}
      #   run: terraform plan -out=plan.tfplan -input=false -lock-timeout=10m
      
      # - name: "Terraform Apply"
      #   working-directory: ./terraform/environments/${{ matrix.env }}
      #   #if: github.event_name == 'push'
      #   run: terraform apply -input=false -lock-timeout=10m plan.tfplan
