name: "provision_adt_schema"

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - "feature**"
    paths:
      - 'terraform/environments/adt/schema/**.tf'
      - 'postgres_resources/**.sql'
      - '.github/workflows/provision_adt_schema.yml'

  pull_request:
    branches:
      - "feature**"
    paths:
     - 'terraform/environments/adt/schema/**.tf'
     - 'postgres_resources/**.sql'
     - '.github/workflows/provision_adt_schema.yml'


jobs:
  run:
    name: "Provision schema"
    runs-on:
      - self-hosted
      - us-west1
    environment: ${{ github.event.pull_request.head.ref }}
    strategy:
      matrix:
        env: ['adt'] #,['adt', 'qat', 'spt'] # Exclude prd from auto-plan
    
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Auth in GCP"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
          project_id: 'p-601-np-membership-adt'

      - name: "Download and setup Cloud SQL Proxy"
        run: |
          # Download Cloud SQL Proxy
          wget https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.0/cloud-sql-proxy.linux.amd64 -O cloud-sql-proxy
          chmod +x cloud-sql-proxy
          
          # Start Cloud SQL Proxy in background
          ./cloud-sql-proxy p-601-np-membership-adt:us-central1:lead-mgmt-adt \
            --port 5432 \
            --private-ip \
            --auto-iam-authn &
          
          # Wait for proxy to be ready
          sleep 10

          # Set access token for IAM DB auth
            export PGPASSWORD=$(gcloud auth print-access-token)

          # Verify connection to database with psql (check connection only, no queries)
            PGPASSWORD="$(gcloud auth print-access-token)" psql \
            "hostaddr=127.0.0.1 port=5432 dbname=lead-mgmt-db user=gco-iam-svc-cicd-mbr-bc-np@gcp-prj-cicd-core.iam sslmode=disable" --no-password -c '\conninfo'

            psql \
            "hostaddr=127.0.0.1 port=5432 dbname=lead-mgmt-db user=gco-iam-svc-cicd-mbr-bc-np@gcp-prj-cicd-core.iam sslmode=disable" \
             --no-password -c 'GRANT ALL PRIVILEGES ON DATABASE "lead-mgmt-db" TO "gco-iam-svc-cicd-mbr-bc-np@gcp-prj-cicd-core.iam";'

          # Verify connection
          echo "Cloud SQL Proxy started successfully"
          
      - name: "Setup Terraform" 
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Init"
        working-directory: ./terraform/environments/${{ matrix.env }}/schema
        run: terraform init

      - name: "Terraform Plan"
        working-directory: ./terraform/environments/${{ matrix.env }}/schema
        run: terraform plan -out=plan.tfplan -input=false -lock-timeout=10m
      
      - name: "Terraform Apply"
        working-directory: ./terraform/environments/${{ matrix.env }}/schema
        run: terraform apply -input=false -lock-timeout=10m plan.tfplan
        env: 
            TF_VAR_gcp_workload_identity_sa_email: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
