name: "provision_prd_schema"

on:
  push:
    tags:
      - release-prd*


jobs:
  run:
    name: "Provision schema"
    runs-on: cw-gcp-us-west1-pd
    environment: ${{ github.event.pull_request.head.ref }}
    strategy:
      matrix:
        env: ['prd']

    permissions:
      id-token: write
      contents: read
      packages: write

    env: 
      TF_VAR_gcp_workload_identity_sa_email: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL_PRD }}
      TF_VAR_db_password: ${{secrets.CLOUD_SQL_PRD_PASSWORD}}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Auth in GCP"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
          project_id: 'p-601-pd-bcleadsmgmt-prd'

      - name: "Install additional utilities"
        run: |
          if ! command -v unzip >/dev/null 2>&1; then
            echo "Installing unzip..."
            sudo apt-get update && sudo apt-get install -y unzip
          else
            echo "unzip is already installed"
          fi 

          if ! command -v psql >/dev/null 2>&1; then
            echo "Installing PostgreSQL client..."
            sudo apt-get update && sudo apt-get install -y postgresql-client
          else
            echo "psql is already installed"
          fi

          if ! command -v node >/dev/null 2>&1; then
            echo "Installing Node.js..."
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
          else
            echo "Node.js is already installed"
          fi

      - name: "Download and setup Cloud SQL Proxy"
        run: |
          if ! command -v cloud-sql-proxy >/dev/null 2>&1; then
            echo "Installing Cloud SQL Auth Proxy..."
            wget https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.0/cloud-sql-proxy.linux.amd64 -O cloud-sql-proxy
            chmod +x cloud-sql-proxy
          else
            echo "Cloud SQL Proxy is already installed"
          fi
          # Start Cloud SQL Proxy in background
          ./cloud-sql-proxy p-601-pd-bcleadsmgmt-prd:us-central1:lead-mgmt-prd \
            --port 5432 \
            --private-ip \
            --auto-iam-authn &
          
          # Wait for proxy to be ready
          sleep 10

          # Set access token for IAM DB auth
          export PGPASSWORD=$(gcloud auth print-access-token)

          # Verify connection to database with psql (check connection only, no queries)
          PGPASSWORD="$(gcloud auth print-access-token)" psql \
            "hostaddr=127.0.0.1 port=5432 dbname=lead-mgmt-db user=gco-iam-svc-cicd-mbr-bc-pd@gcp-prj-cicd-core.iam sslmode=disable" --no-password -c '\conninfo'

          echo "Cloud SQL Proxy started successfully"

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Init"
        working-directory: ./terraform/environments/${{ matrix.env }}/schema
        run: terraform init

      - name: "Terraform Plan"
        working-directory: ./terraform/environments/${{ matrix.env }}/schema
        run: terraform plan -out=plan.tfplan -input=false -lock-timeout=10m

      - name: "Terraform Apply"
        if: startsWith(github.ref, 'refs/tags/release-prd')
        working-directory: ./terraform/environments/${{ matrix.env }}/schema
        run: terraform apply -input=false -lock-timeout=10m plan.tfplan