name: "provision_spt"

on:
  push:
    tags:
      - release-spt*

jobs:
  run:
    name: "Provision infra"
    runs-on: cw-gcp-us-west1-np
    environment: ${{ github.event.pull_request.head.ref }}
    strategy:
      matrix:
        env: ['spt']

    permissions:
      id-token: write
      contents: read

    env:
      TF_VAR_gcp_workload_identity_sa_email: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
      TF_VAR_service_now_client_id: ${{ secrets.SERVICE_NOW_CLIENT_ID }}
      TF_VAR_service_now_client_secret: ${{ secrets.SERVICE_NOW_CLIENT_SECRET }}
      TF_VAR_service_now_username: ${{ secrets.SERVICE_NOW_USERNAME }}
      TF_VAR_service_now_password: ${{ secrets.SERVICE_NOW_PASSWORD }}
      TF_VAR_db_password: ${{secrets.CLOUD_SQL_SPT_PASSWORD}}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Auth in GCP"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
          project_id: 'p-601-np-bcleadsmgmt-spt'

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Init"
        working-directory: ./terraform/environments/${{ matrix.env }}/infra
        run: terraform init

      - name: "Terraform Plan"
        working-directory: ./terraform/environments/${{ matrix.env }}/infra
        run: terraform plan -out=plan.tfplan -input=false -lock-timeout=10m

      - name: "Terraform Apply"
        if: startsWith(github.ref, 'refs/tags/release-spt')
        working-directory: ./terraform/environments/${{ matrix.env }}/infra
        run: terraform apply -input=false -lock-timeout=10m plan.tfplan