name: deploy-snow-sync-job

on:
  workflow_call:
    inputs:
      workflow_trigger_event:
        required: true
        type: string
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER_ID:
        required: true
      GCP_WORKLOAD_IDENTITY_SA_EMAIL:
        required: true
  push:
    branches:
      - main
      - 'feature*'
    tags:
      - release-spt*
      - release-prod*
    paths:
      - .github/workflows/snow_sync_job_deployment.yml
      - lead_management_job/**
      - lead_match_codebase/**


jobs:
  build-and-deploy:
    runs-on:
      - self-hosted
      - us-central1
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: auth
        name: Auth to GCP for GAR service account
        uses : google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID}}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL}}

      - name: Determine environment and conditions
        id: config
        run: |
          REF_NAME="${GITHUB_REF_NAME}"
          REF="${GITHUB_REF}"

          if [[ -z "$WORKFLOW_TRIGGER" ]]; then
           WORKFLOW_TRIGGER="False"
          fi
          echo "WORKFLOW_TRIGGER=$WORKFLOW_TRIGGER"

          get_modified_files() {
            if [[ "${{ github.event.before }}" != "0000000000000000000000000000000000000000" ]]; then
              git diff --name-only "${{ github.event.before }}" "${{ github.sha }}"
            else
              git show --pretty="" --name-only "${{ github.sha }}"
            fi
          }
          
          if [[ "$REF" == refs/heads/feature* ]]; then
            MODIFIED_FILES="$(get_modified_files)"
            echo "$MODIFIED_FILES"
          fi

          if [[ "$WORKFLOW_TRIGGER" == "True" || ("$REF" == refs/heads/feature* && "$MODIFIED_FILES" == *".github/workflows/snow_sync_job_deployment.yml"* )]]; then
            echo "ENV=adt" >> $GITHUB_ENV
            echo "DEPLOY=true" >> $GITHUB_ENV
            echo "PROJECT_ID=p-601-np-bcleadsmgmt-adt" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=gco-iam-svc-lead-mgmt-bc-adt@p-601-np-bcleadsmgmt-adt.iam.gserviceaccount.com" >> $GITHUB_ENV
            echo "ENVIRONMENT_VARIABLES_PATH=./lead_management_job/app_adt.properties" >>  $GITHUB_ENV

          elif [[ "$REF" == refs/heads/main ]]; then
            echo "ENV=qat" >> $GITHUB_ENV
            echo "DEPLOY=true" >> $GITHUB_ENV
            echo "PROJECT_ID=p-601-np-bcleadsmgmt-qat" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=gco-iam-svc-lead-mgmt-bc-qat@p-601-np-bcleadsmgmt-qat.iam.gserviceaccount.com" >> $GITHUB_ENV
             echo "ENVIRONMENT_VARIABLES_PATH=./lead_management_job/app_qat.properties" >>  $GITHUB_ENV

          elif [[ "$REF" == refs/tags/release-spt* ]]; then
            echo "ENV=spt" >> $GITHUB_ENV
            echo "DEPLOY=true" >> $GITHUB_ENV
            echo "PROJECT_ID=p-601-np-bcleadsmgmt-spt" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=gco-iam-svc-lead-mgmt-bc-spt@p-601-np-bcleadsmgmt-spt.iam.gserviceaccount.com" >> $GITHUB_ENV
             echo "ENVIRONMENT_VARIABLES_PATH=./lead_management_job/app_spt.properties" >>  $GITHUB_ENV

          else
            echo "DEPLOY=false" >> $GITHUB_ENV
            echo "BUILD_IMAGE=false" >> $GITHUB_ENV
          fi
        env:
          WORKFLOW_TRIGGER: ${{ inputs.workflow_trigger_event }}

         # elif [[ "$REF" == refs/tags/release-prod* ]]; then
          #  echo "ENV=prod" >> $GITHUB_ENV
          #  echo "DEPLOY=true" >> $GITHUB_ENV
          #  echo "BUILD_IMAGE=false" >> $GITHUB_ENV
          #  echo "PROJECT_ID=p-601-prd-membership-prd" >> $GITHUB_ENV
          #  echo "SERVICE_ACCOUNT=gco-iam-svc-mlty-dbt-prd@p-601-prd-membership-prd.iam.gserviceaccount.com" >> $GITHUB_ENV

      - name: "Prepare env vars for lead matching job"
        id: env
        run: |
          # Filter out comments and blank lines, then join into comma-separated string
          ENV_VARS=$(grep -v '^\s*#' ${{ env.ENVIRONMENT_VARIABLES_PATH }} | grep -v '^\s*$' | paste -sd, -)
          echo "env_vars=$ENV_VARS" >> "$GITHUB_OUTPUT"
      - name: Deploy snow sync job to Cloud Run
        if: env.DEPLOY == 'true'
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          job: 'snow-sync-job'
          image: 'us-docker.pkg.dev/gcp-prj-images/gcp-gar-repo-mbrshp/lead-mgmt:latest'
          project_id: ${{ env.PROJECT_ID }}
          flags: |
            --service-account=${{ env.SERVICE_ACCOUNT }}
            --vpc-egress=all-traffic
            --network=projects/gcp-prj-transit-hub/global/networks/gcp-vpc-np-host
            --subnet=projects/gcp-prj-transit-hub/regions/us-central1/subnetworks/gcp-snt-np-usc1-601-cloudrunjobs-np
            --command="python"
            --args="main.py,snow_to_db"
            --task-timeout=40h 
            --set-env-vars=${{ steps.env.outputs.env_vars }}
            --max-retries=0
            --memory=8Gi
            --cpu=2

      # - name: Deploy cloud run service
      #   if: env.DEPLOY == 'true'
      #   uses: google-github-actions/deploy-cloudrun@v2
      #   with:
      #     service: cloud-scheduler-service
      #     image: 'us-docker.pkg.dev/gcp-prj-images/gcp-gar-repo-mbrshp/cloud-run-service:latest'
      #     project_id: ${{ env.PROJECT_ID }}
      #     flags: |
      #       --service-account=${{ env.SERVICE_ACCOUNT }}
      #       --vpc-egress=all-traffic
      #       --ingress=internal
      #       --network=projects/gcp-prj-transit-hub/global/networks/gcp-vpc-np-host
      #       --subnet=projects/gcp-prj-transit-hub/regions/us-central1/subnetworks/gcp-snt-np-usc1-601-cloudrunjobs-np
      #       --set-env-vars="PROJECT_ID=${{ env.PROJECT_ID }}"

      # - name: Set SERVICE_URL output
      #   if: env.DEPLOY == 'true'
      #   id: get-service-url
      #   run: |
      #     SERVICE_URL=$(gcloud run services describe cloud-scheduler-service \
      #     --project ${{ env.PROJECT_ID }} --region us-central1 --format 'value(status.uri)')
      #     echo "SERVICE_URL=$SERVICE_URL"
      #     echo "service_url=$SERVICE_URL" >> $GITHUB_OUTPUT

      # - name: Add schedule to Cloud Run Job
      #   if: env.DEPLOY == 'true'
      #   run: |
      #     if gcloud scheduler jobs describe snow-sync-job-scheduler \
      #       --project ${{ env.PROJECT_ID }} \
      #       --location us-central1 > /dev/null 2>&1; then
      #       echo "Scheduler job already exists. Skipping creation."
      #     else
      #       echo "Creating scheduler job..."
      #       gcloud scheduler jobs create http snow-sync-job-scheduler \
      #         --project ${{ env.PROJECT_ID }} \
      #         --location us-central1 \
      #         --schedule="0 0 * * *" \
      #         --uri=${{ steps.get-service-url.outputs.service_url }} \
      #         --http-method=GET \
      #         --oidc-service-account-email=${{ env.SERVICE_ACCOUNT }}
      #     fi

      - name: Describe deployed job
        if: env.DEPLOY == 'true'
        run: |
          gcloud run jobs describe snow-sync-job \
            --region us-central1 \
            --project ${{ env.PROJECT_ID }} \
            --format="yaml"
