name: upload-pos-file

on:
  workflow_dispatch:

jobs:

  upload:

    runs-on:
      - self-hosted
      - us-central1

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}

      - name: Upload POS File to GCS
        run: |

          gcloud storage cp \
            pos_match_validation/input/POS/pos_20260521_150207.xlsx \
            gs://gcp-gcs-lead-mgmt-us-qat/pos-validation/input/POS/pos_20260521_150207.xlsx